language: node_js
node_js:
  - 8
script:
  - cd ./smartphone-doctor/
  - npm install
  - npm install -g firebase-tools
  - npm test
  - npm run build
  - firebase deploy --only hosting --token $FIREBASE_TOKEN
branches:
  only:
  - master